version: "3" # The version of docker compose files.
# Each container is a service.
services:
 
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    environment:
        GRID_MAX_SESSION: 16 # Limit os browsers running on this grid.
        GRID_BROWSER_TIMEOUT: 300
        GRID_TIMEOUT: 300
 
  chrome:
    image: selenium/node-chrome
    # Means "selenium/node-chrome" has to wait "selenium-hub"
    # to be up and running before this container is marked as successfully created.
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub # Connect this container to " selenium-hub"
      HUB_PORT_4444_TCP_PORT: 4444
      # This container will have 2 chrome browsers on it.
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    # volumes:
    #   - /dev/shm:/dev/shm
 
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      # This container will have 4 firefox browsers on it.
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
